version: '3' #3
services:
  ros-master:
    image: ros:kinetic-ros-core  #ros:melodic-ros-core
    # container_name: ros_master
    command: stdbuf -o L roscore
    network_mode: host
    restart: always

  viz:
    image: ros:teb #完全版，华中科源，uvc,ros源未添加
    container_name: ros_visualizer_teb
    # depends_on:
    #   - ros-master
    network_mode: host
    environment:
      - "ROS_MASTER_URI=http://127.0.0.1:11311" #设置主机masterhttp://192.168.119.4:11311
      - "ROS_HOSTNAME=192.168.119.4" # 容器
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    user: 1000:1000 # 修改为你的用户ID
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /home/xiosi:/home/xiosi:rw # 修改为你的用户目录
      - /dev:/dev:rw
    # devices:
    #   - /dev/video0:/dev/video0 # 连接相机
    #   - /dev/video1:/dev/video1
    command: rviz #rosrun turtlesim turtlesim_node

